#!/bin/sh -eu

# Read configuration
. "`dirname $0`/matrix.conf"
. "`dirname $0`/functions.sh"

# Is there anyone at Hacklab?
if curl "$visitors/api/v1/hackbus?read=arming_state" | jq -e '.result.arming_state != "Armed"'; then
    echo Hacklab is occupied, not alerting.
    exit
fi

# Unpacking message payload
dir=`mktemp -d`
cd $dir
munpack -t

# Extracting camera name and renaming attachment
export camera_name="`sed -rn 's/^Motion Detected on camera (.*)/\1/p' <part1 | sed 's/ *$//g'`"

# Composing Matrix message. Specs: https://matrix.org/docs/spec/client_server/latest#m-image
room_id="`get_id "$room"`"
matrix POST media/r0/upload image/jpeg <part5 |
    jq '{"body": env.camera_name, "msgtype": "m.image", "url": .content_uri }' |
    matrix PUT "client/r0/rooms/$room_id/send/m.room.message/`uuidgen`" application/json

# Removing the temp dir
rm -r "$dir"
